
export const ACTION_CART = {
    ADD_ITEM: "ACTION_CART_ADD_ITEM",
    GET_LIST_CART: 'ACTION_CART_GET_LIST_CART',
    INCREASE_ITEM: "ACTION_CART_INCREASE_ITEM",
    DECREASE_ITEM: "ACTION_CART_DECREASE_ITEM",
    REMOVE_ITEM: "ACTION_CART_REMOVE_ITEM"
};

export const ACTION_FOOD_DETAIL = {
    INCREASE: "ACTION_FOOD_DETAIL_INCREASE",
    DECREASE: "ACTION_FOOD_DETAIL_DECREASE",
    SIZE_SELECT: "ACTION_FOOD_DETAIL_SELECT_SIZE",
    ADD: "ACTION_FOOD_DETAIL_ADD"
};

export const ACTION_AUTHENTICATION = {
    LOGIN: "ACTION_LOGIN",
    LOGOUT: "ACTION_LOGOUT",
    LOGIN_SUCCESS: "ACTION_LOGIN_SUCCESS",
    LOGIN_FAIL: "ACTION_LOGIN_FAIL",
    SET_LOADING: "ACTION_AUTHENTICATION_SET_LOADING",
};